name: 📌 AIOps Task
description: Create a new issue to track a specific AIOps-related task.
title: "[Task] <Write a clear, short task title>"
labels: ["task", "AIOps", "internship"]
assignees:
  - your-github-username
body:
  - type: input
    id: objective
    attributes:
      label: 🎯 Objective
      description: What is the purpose of this task?
      placeholder: "e.g., Install and configure Prometheus for local metrics monitoring"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Task Checklist
      description: Break the task down into steps
      options:
        - label: Research or review required concepts
        - label: Set up any necessary tools or environments
        - label: Write or configure code/scripts
        - label: Test and validate the solution
        - label: Document outcome (screenshot, log, notes)

  - type: textarea
    id: notes
    attributes:
      label: 📝 Notes / Progress
      description: Add any details, logs, problems, or thoughts as you work on the task.
      placeholder: |
        - Installed Prometheus using Docker
        - Faced an issue binding to port 9090, fixed by stopping another service
        - Will document steps in wiki
    validations:
      required: false
